permalink: /:title/
markdown: kramdown
highlighter: true

kramdown:
  input: GFM

# 作者信息
author: 
  name: 綠茶
  link: http://vc2tea.com
  Twitter: https://twitter.com/vc2tea

# 站点信息
title: 綠茶如是说 
description: 我们走得太快，灵魂都跟不上了
url: http://vc2tea.com
rss_url: /pages/atom.xml

# gavatar头像及Favicon
avatar: /public/img/avatar.jpg
favicon: /public/img/favicon.ico

# google analytics 设置
# ga:
#   id: UA-xxxxxxxx-1
#   url: vc2tea.com

# disqus 设置
disqus:
  shortname: vc2tea
